### ISSUE TITLE
persona_database.npy

### ISSUE THREAD

**Issue by ssw03270** [AlanJiang98/DLP-SocioMind#1]
I clicked the assets button to download the persona_database.npy, but the link is not functioning properly. 
Could you help me resolve this issue?

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by AlanJiang98** [comment]
There was an unfortunate accident at our data host that led to invalid download links. We are in the midst of resolving these issues. You can send me an email, then I'll attach the assets to you.
My email: alanjjp98@gmail.com

**Comment by caizhongang** [comment]
The assets are now hosted on Google Drive and have been online again :)
